# Generated by Django 5.0.14 on 2026-04-29 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_attempt', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec connexion'), ('OTP_REQUIRED', 'OTP requis'), ('OTP_SUCCESS', 'OTP validé'), ('OTP_FAILED', 'OTP échoué')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
