# Generated by Django 5.0.14 on 2026-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authauditlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec connexion'), ('OTP_REQUIRED', 'OTP requis'), ('OTP_SUCCESS', 'OTP validé'), ('OTP_FAILED', 'OTP échoué'), ('ACCOUNT_LOCKED', 'IP bloquée'), ('SUSPICIOUS_LOGIN', 'Connexion suspecte')], max_length=30),
        ),
    ]
