# Generated by Django 5.0.14 on 2026-04-20 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Système'), ('MINISTRE', 'Ministre de la Justice'), ('DIRECTEUR', 'Directeur de Prison'), ('MEDECIN', 'Service Médical'), ('INTENDANT', 'Logistique & Intendance'), ('AGENT', 'Agent de Détention'), ('SECURITE', 'Chef de Sécurité')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Système'), ('MINISTRE', 'Ministre de la Justice'), ('DIRECTEUR', 'Directeur de Prison'), ('MEDECIN', 'Service Médical'), ('INTENDANT', 'Logistique & Intendance'), ('AGENT', 'Agent de Détention'), ('SECURITE', 'Chef de Sécurité')], db_index=True, default='AGENT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
