# Generated by Django 5.0.14 on 2026-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_permission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Système'), ('MINISTRE', 'Ministre de la Justice'), ('DIRECTEUR', 'Directeur de Prison'), ('GREFFIER', 'Greffier De la Justice'), ('MEDECIN', 'Service Médical'), ('INTENDANT', 'Logistique & Intendance'), ('AGENT', 'Agent de Détention'), ('SECURITE', 'Chef de Sécurité')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Système'), ('MINISTRE', 'Ministre de la Justice'), ('DIRECTEUR', 'Directeur de Prison'), ('GREFFIER', 'Greffier De la Justice'), ('MEDECIN', 'Service Médical'), ('INTENDANT', 'Logistique & Intendance'), ('AGENT', 'Agent de Détention'), ('SECURITE', 'Chef de Sécurité')], db_index=True, default='AGENT', max_length=20),
        ),
    ]
