# Generated by Django 5.0.14 on 2026-04-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreinteDigitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_empreinte', models.CharField(help_text="Identifiant unique de l'empreinte (hash / template)", max_length=255, unique=True)),
                ('qualite', models.PositiveSmallIntegerField(default=0, help_text="Qualité de l'empreinte (0 à 100)")),
                ('appareil', models.CharField(blank=True, help_text='Nom du scanner biométrique', max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('detenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empreinte', to='core.detenu')),
            ],
            options={
                'verbose_name': 'Empreinte Digitale',
                'verbose_name_plural': 'Empreintes Digitales',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='ReconnaissanceFaciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(help_text='Identifiant unique facial (vector / encoding)', max_length=255, unique=True)),
                ('score_confiance', models.PositiveSmallIntegerField(default=0, help_text='Score de confiance (0 à 100)')),
                ('camera', models.CharField(blank=True, help_text='Caméra utilisée pour la capture', max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('detenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='core.detenu')),
            ],
            options={
                'verbose_name': 'Reconnaissance Faciale',
                'verbose_name_plural': 'Reconnaissances Faciales',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
