# Generated by Django 5.0.14 on 2026-04-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detenu',
            name='autorite_judiciaire',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detenu',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detenu',
            name='contact_urgence_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detenu',
            name='lien_parente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detenu',
            name='regime_alimentaire',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
