# Generated by Django 5.0.14 on 2026-04-20 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detenu_autorite_judiciaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaudit',
            options={'ordering': ['-date_action']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='derniere_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='historiquearticle',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='date_mouvement',
        ),
        migrations.AddField(
            model_name='traceuraudit',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agent',
            name='contact_urgence_nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='corvee',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('INCIDENT', 'Incident')], default='EN_COURS', max_length=50),
        ),
    ]
