# Generated by Django 5.0.14 on 2026-04-24 13:07

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journalaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceuraudit',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deces', models.DateTimeField(default=django.utils.timezone.now)),
                ('cause', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ENQUETE', 'Enquête en cours')], default='EN_ATTENTE', max_length=20)),
                ('certificat', models.FileField(blank=True, null=True, upload_to='certificats_deces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declare_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_declares', to=settings.AUTH_USER_MODEL)),
                ('detenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detenu')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.AuditMixin, models.Model),
        ),
    ]
