# Generated by Django 5.0.14 on 2026-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_traceuraudit_object_id_deces'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
