# Generated by Django 5.0.14 on 2026-04-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_derniere_mise_a_jour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deces',
            options={'ordering': ['-date_deces'], 'verbose_name': 'Décès'},
        ),
        migrations.RemoveField(
            model_name='deces',
            name='created_at',
        ),
        migrations.AddField(
            model_name='deces',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deces',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deces',
            name='detenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deces_records', to='core.detenu'),
        ),
    ]
